import 'jnat-get-ui-core/dist/theme/default.css'
import 'jnat-get-ui-core/dist/theme/gt.css'
import './assets/style/csshake.min.css'
import './assets/style/index.less'
import './assets/style/gt_ui_fixed.less'
import './assets/style/iconfont.css'
